apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/router.ex
defmodule TarantulaFriendFinderWeb.Router do
  use TarantulaFriendFinderWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    #plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug TarantulaFriendFinderWeb.Authentication.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :ensure_not_auth do
    plug Guardian.Plug.EnsureNotAuthenticated
  end

  pipeline :auth_html_errors do
    plug Guardian.Plug.Pipeline, error_handler: AuthMe.UserManager.ErrorHandlers.HTML
  end

  pipeline :auth_json_errors do
    plug Guardian.Plug.Pipeline, error_handler: AuthMe.UserManager.ErrorHandlers.JSON
  end

  # BROWSER

  # definitely logged in scope
  scope "/", TarantulaFriendFinderWeb do
    pipe_through [:browser, :auth, :ensure_auth, :auth_html_errors]

    scope "/auth" do
      get "/test", AuthController, :test
      get "/logout", AuthController, :logout
    end

    get "/users/edit", UserController, :edit
  end

  # definitely not logged in scope
  scope "/", TarantulaFriendFinderWeb do
    pipe_through [:browser, :auth, :ensure_not_auth, :auth_html_errors]

    scope "/auth" do
      post "/", AuthController, :authenticate
      get "/login", AuthController, :login
    end

    get "/users/new", UserController, :new
  end

  # maybe logged in scope
  scope "/", TarantulaFriendFinderWeb do
    pipe_through [:browser, :auth, :auth_html_errors]

    get "/", SearchController, :index

    get "/users/:id", UserController, :show
  end
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/controllers/auth_controller.ex
defmodule TarantulaFriendFinderWeb.AuthController do
  use TarantulaFriendFinderWeb, :controller
  alias TarantulaFriendFinderWeb.Authentication, as: Auth

  def authenticate(conn, params) do
    username = params["username"]
    password = params["password"]
    Identity.login(username, password)
    |> authenticate_reply(conn)
  end

  defp authenticate_reply({:ok, user}, conn) do
    conn
    |> Guardian.Plug.sign_in(Auth.Guardian, user)
    |> redirect(to: Routes.search_path(conn, :index))
  end
  defp authenticate_reply(:error, conn) do
    redirect(conn, to: Routes.auth_path(conn, :login, [error: true]))
  end

  def login(conn, params) do
    render(conn, "login.html", [error_feedback:  error_feedback(params)])
  end

  defp error_feedback(%{"error" => "true"}), do: "Invalid username or password."
  defp error_feedback(_), do: nil

  def logout(conn, params) do
    conn
    |> Guardian.Plug.sign_out(Auth.Guardian, [])
    |> redirect(to: Routes.auth_path(conn, :login))
  end

  def test(conn, params) do
    user = Guardian.Plug.current_resource(conn)
    render(conn, "test.html", current_user: user)
  end
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/controllers/search_controller.ex
defmodule TarantulaFriendFinderWeb.SearchController do
  use TarantulaFriendFinderWeb, :controller

  def index(conn, params) do
    render(conn, "index.html", [form_partial: nil])
  end
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/controllers/user_controller.ex
defmodule TarantulaFriendFinderWeb.UserController do
  use TarantulaFriendFinderWeb, :controller

  def show(conn, %{"id" => id } = params) do
    render(conn, "show.html", [])
  end

  def new(conn, params) do
    render(conn, "new.html", [
      username_feedback: nil,
      password_feedback: nil,
      password_confirmation_feedback: nil,
      email_feedback: nil,
      email_confirmation_feedback: nil,
      loading: false
      ])
  end

  def edit(conn, params) do
    render(conn, "edit.html", [edit_partial: :change_password])
  end
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/views/auth_view.ex
defmodule TarantulaFriendFinderWeb.AuthView do
  use TarantulaFriendFinderWeb, :view

  def form_class(nil), do: "text-left needs-validation"
  def form_class(_), do: "text-left"

  def input_class(nil), do: "form-control"
  def input_class(_), do: "form-control is-invalid"
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/views/bootstrap_view.ex
defmodule TarantulaFriendFinderWeb.BootstrapView do
  use TarantulaFriendFinderWeb, :view
  import Phoenix.HTML

  @doc """
  CSS input class.  Can provide a feedback `String.t` in order to set the "is-invalid" class
  when said `feedback` is not `nil`.
  """
  def input_class(feedback \\ nil)
  def input_class(nil), do: "form-control"
  def input_class(_feedback), do: "form-control is-invalid"

  @doc """
  Adds a CSS class for invalid form input feedback text if any feedback is actually given.
  Can be used on a fresh form with a value of `nil` when no feedback will be displayed.
  """
  def feedback_class(feedback \\ nil)
  def feedback_class(nil), do: ""
  def feedback_class(_feedback), do: "invalid-feedback"
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/views/error_view.ex
defmodule TarantulaFriendFinderWeb.ErrorView do
  use TarantulaFriendFinderWeb, :view

  def render("400.json", %{reason: reason}) do
    %{
      error: "bad request",
      reason: reason
    }
  end

  def render("401.json", %{body: body}) do
    %{
      error: body
    }
  end

  def render("401.json", _assigns) do
    %{
      error: "unauthorized"
    }
  end

  def render("403.json", _assigns) do
    %{
      error: "forbidden"
    }
  end

  def render("404.json", _assigns) do
    %{
      error: "not found"
    }
  end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/views/layout_view.ex
defmodule TarantulaFriendFinderWeb.LayoutView do
  use TarantulaFriendFinderWeb, :view

  def current_user(conn) do
    Guardian.Plug.current_resource(conn)
  end
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/views/search_view.ex
defmodule TarantulaFriendFinderWeb.SearchView do
  use TarantulaFriendFinderWeb, :view
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/views/user_view.ex
defmodule TarantulaFriendFinderWeb.UserView do
  use TarantulaFriendFinderWeb, :view
end

apps/tarantula_friend_finder_web/lib/tarantula_friend_finder_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title>TarantulaFriendFinder · Phoenix Framework</title>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/darkly/bootstrap.min.css" rel="stylesheet" integrity="sha384-w+8Gqjk9Cuo6XH9HKHG5t5I1VR4YBNdPt/29vwgfZR485eoEJZ8rJRbm3TR32P6k" crossorigin="anonymous">
    <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"-->
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section>
        <nav role="navigation" class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
          <div class="container">
            <%= link("Tarantula Friend Finder", to: Routes.search_path(@conn, :index), class: "navbar-brand") %>
            <ul class="navbar-nav">
              <li class="navbar-item">
                <a class="nav-link" href="#">Link 1</a>
              </li>
              <li class="navbar-item">
                <a class="nav-link" href="#">Link 2</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
            <%= case current_user(@conn) do %>
              <% nil -> %>
                <li class="navbar-item">
                  <%= link("Sign In", to: Routes.auth_path(@conn, :login), class: "nav-link") %>
                </li>
                <li class="navbar-item">
                  <%= link("Register", to: Routes.user_path(@conn, :new), class: "nav-link") %>
                </li>
              <% user -> %>
                <div class="nav-item dropdown ml-auto">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown">
                    <%= user.username %>
                  </a>
                  <div class="dropdown-menu">
                    <%= link("Profile", to: Routes.user_path(@conn, :show, user.id), class: "dropdown-item") %>
                    <%= link("Manage", to: Routes.user_path(@conn, :edit), class: "dropdown-item") %>
                    <%= link("Sign Out", to: Routes.auth_path(@conn, :logout), class: "dropdown-item") %>
                  </div>
                </div>
            <% end %>          
            </ul>
          </div>
        </nav>
        <!--a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a-->
      </section>
    </header>
    <main role="main" class="container vh-100">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <%= Drab.Client.run(@conn) %>
  </body>
</html>